SVG export: add image size
excalidraw/excalidraw pull request #2292
Opened 2020-10-27 21:18 UTC by geraintluff

The SVG root element has no width/height, so they end up drawn at unspecified size

Includes "width" and "height" attributes in root SVG element, including 1x/2x/3x scaling.

Fixes #2291

2020-10-27 23:53 UTC, lipis requested changes
Do we really need this? What's the use case? You can always change the size in wherever you're using that SVG..

2020-10-28 15:54 UTC, dwelle commented
I tend to agree. It's more intuitive for the SVG to fit to container by default, and it's easy to constrain the size via CSS or editing the SVG file, if needed.

2020-10-28 16:44 UTC, geraintluff commented
My use-case is that I draw a lot of individual diagrams, and embed them in web-pages as images.

Without size information, these draw at all different scales. One diagram (which was "larger") draws with thin lines and small text, but another (which was "smaller") is drawn with giant lines.

With PNGs, this works as expected: the diagrams _have_ an inherent size, which is used both for PNG export (that's why "2x" is meaningful), and also as displayed in Excalidraw itself!

That size information is lost in SVG export.  My current workaround is: open the SVG, look at the viewport size, and add that explicitly to either the HTML embedding or the SVG itself - either way, this has to be re-done when editing the diagram, because that might change the size.

Anywhere the size is specified with CSS or whatever would still work.

2020-10-28 17:02 UTC, lipis approved these changes

2020-10-28 17:10 UTC, merged