use icon for text align property
excalidraw/excalidraw pull request #2379
Opened 2020-11-14 13:43 UTC by nschnierer

<img width="287" alt="Bildschirmfoto 2020-11-03 um 13 12 53" src="https://user-images.githubusercontent.com/3831579/99148369-880e2180-2687-11eb-9ed0-1f796cfbe7cc.png">

See #2201

2020-11-14 16:20 UTC, lipis commented on src/actions/actionProperties.tsx
> +  TextAlignRight,
maybe add `Icon` for consistency with other icons

2020-11-14 16:42 UTC, dwelle commented
:+1:

I'd align the size with rest of the icons, though:

![image](https://user-images.githubusercontent.com/5153846/99152220-b5b39480-26a0-11eb-807b-880ab9b9b680.png)

2020-12-03 17:55 UTC, lipis commented
@dwelle I think they are properly aligned with the rest of the icons there.. eventually we'll change the rest of font related ones to icons as well and everything will be aligned :)
<img width="201" alt="Screenshot 2020-12-03 at 7 53 40 PM" src="https://user-images.githubusercontent.com/125676/101068360-4fd07380-35a1-11eb-956f-9ec68ffaf411.png">

2020-12-03 18:03 UTC, dwelle commented
Alright, let's keep it.

One thing though, changing to the svg/button or whatever it is now introduced a regression: when you're editing text and change text align, it now confirms (exits) the editor.

2020-12-05 19:36 UTC, steveruizok commented
![image](https://user-images.githubusercontent.com/23072548/101261646-ccde2300-3730-11eb-97c7-16efc44bc1f9.png)

Whimsical has a pretty good UI for font size / text alignment. Would something like this work for Excalidraw? (Font family would break the mold a bit.)

2020-12-17 20:46 UTC, lipis approved these changes

2020-12-18 17:04 UTC, dwelle commented
Before merging, we still need to fix the UX regression: https://github.com/excalidraw/excalidraw/pull/2379#issuecomment-738182782

2020-12-18 17:20 UTC, lipis commented
@dwelle  I was just about to comment on that..!

2020-12-18 17:20 UTC, lipis requested changes
> One thing though, changing to the svg/button or whatever it is now introduced a regression: when you're editing text and change text align, it now confirms (exits) the editor.

2021-02-11 12:45 UTC, dwelle commented
Closing in favor of https://github.com/excalidraw/excalidraw/pull/2857

2021-02-11 12:45 UTC, closed without merging