feat: Implement the Web Share API for the collaboration dialog
excalidraw/excalidraw pull request #3222
Opened 2021-03-10 18:27 UTC by h7y

As discussed in the issue, share button will replace the copy button if the browser supports it. Since Safari web also supports this, the behavior is same there. Is that fine?

![Demo on iPhone simulator](https://media.giphy.com/media/bGDEAPHW3GNg96QrZb/giphy.gif)

2021-03-10 20:02 UTC, dwelle commented
Thanks for the speedy PR.

A few notes:

- Unclear whether we should replace the button on Desktop (or even a mobile) as opposed to showing both. For example, on Safari desktop, the share menu doesn't contain `copy to clipboard` — but, copying by selecting and pressing `cmd+c` is easy though.
- If you do `copy to clipboard`, it sadly can't be differentiated and puts in the preface text with "join the session" etc. This is useful when sharing on social, or sending via email, but if you need to copy just copy the link, it's not. But again, probably not a big deal.
- On the only non-safari desktop browser that supports it, Edge, the button doesn't do anything (at least on Windows). Maybe we should dispense with desktop browsers altogether?
- Let's catch a cancellation error and mute it instead of displaying it. In my tests it showed the error all the time, even if I confirmed by copying to clipboard.

Let's wait for @tomayac's thoughts.

2021-03-11 07:22 UTC, tomayac requested changes
Thanks so much for working on this. I have left a couple of suggestions. I’m open to leaving both buttons, copy link and share link, for the same arguments that @dwelle brought forward. 

Can you try how it looks like with two buttons? Their icons plus tool tips are hopefully distinguishable enough, especially since we go with each platform’s default share icon that people will immediately recognize. 

For desktop browsers, this API is coming to desktop Chromium (and therefore Chrome & Edge). The feature detection might be positive, even when the API is not implemented yet, if you have set the “experimental web platform features” flag or are using a non-stable branch like beta, dev, or canary. It’s not a problem on 99.999% of browser versions that people use in the wild. 😃

2021-03-11 07:22 UTC, tomayac commented on src/excalidraw-app/collab/RoomDialog.tsx
> +      setErrorMessage(error.message);
```suggestion
      // Just ignore.
```

2021-03-11 07:22 UTC, tomayac commented on src/excalidraw-app/collab/RoomDialog.tsx
> +              {navigator.share ? (
```suggestion
              {"share" in navigator ? (
```

2021-03-11 07:22 UTC, tomayac commented on src/locales/en.json
> +    "shareTitle": "Join live collaboration on Excalidraw"
```suggestion
    "shareTitle": "Join a live collaboration session on Excalidraw"
```

2021-03-11 08:10 UTC, h7y commented
> Can you try how it looks like with two buttons? Their icons plus tool tips are hopefully distinguishable enough, especially since we go with each platform’s default share icon that people will immediately recognize.
![Simulator Screen Shot - iPhone 12 Pro Max - 2021-03-11 at 13 37 20](https://user-images.githubusercontent.com/22396000/110755624-2ba2c380-826f-11eb-9dc2-d48cf2402cd3.png)

2021-03-11 09:02 UTC, tomayac approved these changes
LGTM

This looks and works fantastic! Thanks so much for working on this!

2021-03-11 10:49 UTC, lipis approved these changes

2021-03-11 11:21 UTC, merged