fix: free draw elements move on flip
excalidraw/excalidraw pull request #5583
Opened 2022-08-17 14:45 UTC by alex-kim-dev

Single element, `shift + h` or `shift + v` or through the context menu:

![Peek 2022-08-17 19-41](https://user-images.githubusercontent.com/45559664/185167771-725bf5b2-bb31-44a4-8058-de848c05b017.gif)

2022-09-02 14:13 UTC, alex-kim-dev commented
It would be great to get a review for this pr too, thanks!

2022-10-15 15:48 UTC, DanielJGeiger requested changes
The code added by this PR seems good to me!  By removing the code for flipping linear elements, this PR caused a regression there.  My suggested changes essentially restore the removed code to fix the regression.

@dwelle @ad1992

2022-10-15 15:48 UTC, DanielJGeiger commented on src/actions/actionFlip.ts
> -import { LinearElementEditor } from "../element/linearElementEditor";
Keep this import.

2022-10-15 15:48 UTC, DanielJGeiger commented on src/actions/actionFlip.ts
> +  if (isLinearElement(element) || isFreeDrawElement(element)) {
```suggestion
  if (isFreeDrawElement(element)) {
```

2022-10-15 15:48 UTC, DanielJGeiger commented on src/actions/actionFlip.ts
>    } else {
```suggestion
  } else if (isLinearElement(element)) {
    for (let index = 1; index < element.points.length; index++) {
      LinearElementEditor.movePoints(element, [
        { index, point: [-element.points[index][0], element.points[index][1]] },
      ]);
    }
    LinearElementEditor.normalizePoints(element);
  } else {
```

2022-10-21 05:31 UTC, closed without merging

2022-10-21 05:31 UTC, alex-kim-dev commented
Closing because the issue is fixed already