feat: keep customData when converting to ExcalidrawElement (#7654)
excalidraw/excalidraw pull request #7656
Opened 2024-02-05 14:00 UTC by yubinTW

for #7654 

if `customData` of an `ExcalidrawElementSkeleton` is provided, when using `convertToExcalidrawElements()` to convert `ExcalidrawElementSkeleton` to `ExcalidrawElement`,  it will not disappear.

2024-02-06 05:53 UTC, ad1992 requested changes
Thanks for the PR @yubinTW

2024-02-06 05:53 UTC, ad1992 commented on packages/excalidraw/data/transform.test.ts
> +      expect(ele.customData).not.toBeDefined();
separate test not needed, its already recorded in snapshot

2024-02-06 05:53 UTC, ad1992 commented on packages/excalidraw/data/transform.test.ts
> +        type: "image",
just a single element is enough, also lets move this test towards the end

2024-02-06 11:17 UTC, yubinTW commented
Hi @ad1992,
Thanks for the reviews, I had updated the test case.

2024-02-07 13:19 UTC, krzysztofMlczk commented
@ad1992 can this be merged?

2024-02-07 13:44 UTC, ad1992 requested changes
@yubinTW can you also update the package changelog ? Also this should under Fixes category in changelog

2024-02-07 15:09 UTC, yubinTW commented
Hi @ad1992
Sure, updated the CHANGELOG.

2024-02-08 11:33 UTC, krzysztofMlczk commented
@ad1992 when can we expect patch with those changes?

2024-02-08 11:40 UTC, ad1992 approved these changes

2024-02-08 11:53 UTC, merged

2024-02-08 11:55 UTC, ad1992 commented
> @ad1992 when can we expect patch with those changes?

very soon, I will check if there is anything else we should push to patch and release by tonight/tomorrow.

2024-02-09 09:41 UTC, ad1992 commented
> @ad1992 how can I know that the patch is out?

I will be sharing here once the patch is released so post that you can update it