fix: #8475 Arrow updated on both sides
excalidraw/excalidraw pull request #8593
Opened 2024-10-03 23:52 UTC by ritk20

Arrow updates on both sides when moving connected objects (issue: #8475)

However, when a smaller shape is inside a bigger one, the updates are too rapid and may not be desirable.

2024-10-22 17:03 UTC, mtolmacs requested changes

2024-10-22 17:03 UTC, mtolmacs commented on packages/excalidraw/element/binding.ts
> +          (bindingProp === "startBinding" || bindingProp === "endBinding")
This change will run updateBoundPoint(...) for all scene elements, which is a large amount of no-op for every movement of even a single arrow connected shape. Instead you should set up the condition that either the changed bindable element is true or the connected other end element.

2024-10-23 08:39 UTC, mtolmacs commented
Looks good, but if we fix the situation when both sides of an arrow is bound, we should look into fixing the case when only one side of the arrow is bound to remain consistent:
![arrowupdate](https://github.com/user-attachments/assets/bb04ef95-f384-4810-ad56-d7bd0eb68672)

2024-10-23 08:48 UTC, ritk20 commented
makes sense, let me try that as well!

2024-10-25 09:14 UTC, ritk20 commented
I am facing some difficulties in arrow movement, specifically how the arrow handles transforming. Specifically, when the `transformElements(...)` function is called from packages/excalidraw/element/resizeElements.ts, I am able to get the desired behavior in arrow handling using the below code in `updateBoundElements(...)` function of binding.ts.

`if (isBindingElement(changedElement)) {
    if (changedElement.startBinding) {
      const element = elementsMap.get(changedElement.startBinding.elementId);
      if (element) {
        updateBoundElements(element, elementsMap, options);
      }
    }
    if (changedElement.endBinding) {
      const element = elementsMap.get(changedElement.endBinding.elementId);
      if (element) {
        updateBoundElements(element, elementsMap, options);
      }
    }
  }`
  
However, many times when moving the arrowend, the `transformElements(...)` function is not called rather the `handlePointDragging(...)` function is called from packages/excalidraw/element/linearElementEditor.ts, which doesnot call the `updateBoundElements(...)` function, and thus there is no update in the bounded side of the arrow.

2024-10-25 10:50 UTC, mtolmacs commented
Yes, most likely binding update needs to be called when the handles are dragged, if the arrow is connected on the other end.

2024-10-25 13:53 UTC, ritk20 commented
Works fine

https://github.com/user-attachments/assets/0b3a89bd-8fbc-4e07-8f60-71c2264304ed

2024-10-27 09:48 UTC, mtolmacs commented
...except  now you can't unbind a bound arrow @ritk20 :)
![unbind](https://github.com/user-attachments/assets/a51120b9-11c0-44f2-bf91-6d24c398fcf9)

2024-10-28 17:54 UTC, ritk20 commented
There are some issues with this one, like 

https://github.com/user-attachments/assets/3de34bba-2cea-4db4-83ce-03eb42170dfd

and sometimes the arrow is just bound to the corners

|

https://github.com/user-attachments/assets/7907d4f7-bfe7-4b66-b6a7-2944da24a3f9

Am trying to fix these issues now

2024-11-18 16:23 UTC, mtolmacs commented
Hi @ritk20 ,

Sorry for not getting back sooner. The corner case looks okay as it is, it's because how focus point tracking is implemented and there will be an improvement happening sometime soon, which I expect will resolve this issue.

However it's a little problematic when you [drag a connected shape over the other](https://excalidraw-18uu4p7g2-excalidraw.vercel.app/#json=aKJZcLFoKs_hdUaArc01J,BL1tB8S1KmtREKD9Tf0mPg).

Maybe in this case we should fall back on the old behavior while they overlap?

2024-11-29 05:50 UTC, ritk20 commented
should the updates stop (according to old behaviour) for both boxes or only for the un-dragged box? Which option looks better?

2024-11-29 16:44 UTC, mtolmacs commented
I prefer the current behavior, maybe @dwelle has a different opinion?

2025-03-04 15:45 UTC, dwelle approved these changes

2025-03-04 16:18 UTC, mtolmacs approved these changes

2025-03-04 16:24 UTC, merged

2025-03-04 16:25 UTC, mtolmacs commented
Sorry for taking so, so long again, merged! Thanks for your contribution @ritk20!